function equation_system = equation_system_function_3(dircos)

global z1 z2 z3

equation_system = [dircos(1)*dircos(2) + dircos(4)*dircos(5) + z1*z2; ...
                   dircos(1)*dircos(3) + dircos(4)*dircos(6) + z1*z3; ...
                   dircos(2)*dircos(3) + dircos(5)*dircos(6) + z2*z3; ...
                   dircos(1)^2 + dircos(4)^2 + z1^2 - 1; ...
                   dircos(2)^2 + dircos(5)^2 + z2^2 - 1; ...
                   dircos(3)^2 + dircos(6)^2 + z3^2 - 1; ...
                   dircos(2)*dircos(6) - dircos(3)*dircos(5) - z1; ...
                   dircos(3)*dircos(4) - dircos(1)*dircos(6) - z2; ...
                   dircos(1)*dircos(5) - dircos(2)*dircos(4) - z3];