function equation_system = equation_system_function(dircos)

global x3 y2 y3

equation_system = [dircos(1)*dircos(2) + dircos(3)*y2 + dircos(4)*dircos(5); ...
                   dircos(1)*x3 + dircos(3)*y3 + dircos(4)*dircos(6); ...
                   dircos(2)*x3 + y2*y3 + dircos(5)*dircos(6); ...
                   dircos(1)^2 + dircos(3)^2 + dircos(4)^2 - 1; ...
                   dircos(2)^2 + y2^2 + dircos(5)^2 - 1; ...
                   x3^2 + y3^2 + dircos(6)^2 - 1];